CREATE TABLE [dbo].[Courier]
(
	[Id] INT NOT NULL IDENTITY(0,1),
	[Name] VARCHAR(50) NOT NULL,
	[InitialCost] DECIMAL(7,2) NOT NULL,
	[WeightFee] DECIMAL(7,2) NOT NULL,
	CONSTRAINT PK_Courier_Id PRIMARY KEY (Id)
)
